name: Deploy to Hetzner with Ansible

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ansible
        uses: dawidd6/action-install-ansible@v2
        with:
          version: 'latest'

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.HETZNER_SSH }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Run Ansible Playbook without Inventory
        run: |
          ansible-playbook deploy.yml \
            --extra-vars "server_ip=${{ secrets.SERVER_IP }}" \
            --extra-vars "ssh_key=${{ secrets.HETZNER_SSH }}" \
            --extra-vars "NEXT_PUBLIC_STRAPI_API_URL=${{ secrets.NEXT_PUBLIC_STRAPI_API_URL }}" \
            --extra-vars "APP_KEYS=${{ secrets.APP_KEYS }}" \
            --extra-vars "API_TOKEN_SALT=${{ secrets.API_TOKEN_SALT }}" \
            --extra-vars "ADMIN_JWT_SECRET=${{ secrets.ADMIN_JWT_SECRET }}" \
            --extra-vars "TRANSFER_TOKEN_SALT=${{ secrets.TRANSFER_TOKEN_SALT }}" \
            --extra-vars "DATABASE_CLIENT=${{ secrets.DATABASE_CLIENT }}" \
            --extra-vars "DATABASE_FILENAME=${{ secrets.DATABASE_FILENAME }}" \
            --extra-vars "JWT_SECRET=${{ secrets.JWT_SECRET }}" \
            --extra-vars "DATABASE_SSL=${{ secrets.DATABASE_SSL }}" \
            --extra-vars "HOST=${{ secrets.HOST }}" \
            --extra-vars "PORT=${{ secrets.PORT }}"
