name: Merge to Main Workflow

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build docker files"]
      - completed

jobs:
  merge:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge to main branch
        run: |
          git config --global user.email "{secret.GITHUB_EMAIL}"
          git config --global user.name "{secret.GITHUB_USERNAME}"
          git checkout main
          git merge ${{ github.head_ref }}  # This merges the feature branch into the main branch
          git push origin main
