name: Merge to Main Workflow

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build docker files"]
    types:
      - completed

jobs:
  merge:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout feature branch
        run: |
          git fetch origin ${{ vars.BRANCH_NAME }}
          git checkout ${{ vars.BRANCH_NAME }}

      - name: Checkout the main branch
        run: |
          git fetch origin main
          git checkout main

      - name: Merge feature branch into main
        run: |
          git merge ${{ vars.BRANCH_NAME }}
          git push origin main
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
