name: Merge to Main Workflow

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build docker files"]
    types:
      - completed

jobs:
  merge:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Branch Name Artifact
        uses: actions/download-artifact@v4
        with:
          name: branch-name
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Unzip and Get Branch Name
        run: |
          BRANCH_NAME=$(cat branch_name.txt)
          echo "Branch to merge: $BRANCH_NAME"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV  

      - name: Debug Environment Variable
        run: echo "Persisted Branch Name: $BRANCH_NAME"
      
      - name: Checkout feature branch
        run: |
          git fetch origin $BRANCH_NAME
          git checkout $BRANCH_NAME

      - name: Checkout the main branch
        run: |
          git fetch origin main
          git checkout main

      - name: Merge feature branch into main
        run: |
          git merge $BRANCH_NAME
          git push origin main