name: OWASP ZAP Security Scan

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Deploy to Hetzner"]
    types:
      - completed

jobs:
  security-scan:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Wait for page to be accessible
      run: |
        echo "Waiting for the application to be accessible..."
        until curl --silent --fail "http://{secret.SERVER_IP}:3000"; do
          echo "Waiting for the server to be ready..."
          sleep 5
        done
        echo "Server is now accessible."

    - name: Run OWASP ZAP Security Scan
      uses: zaproxy/action-full-scan@v0.5.0
      with:
        target: 'http://{secret.SERVER_IP}:3000'
        wait-for-scan: 'true'

    - name: Upload ZAP Scan Report
      uses: actions/upload-artifact@v2
      with:
        name: zap-scan-report
        path: zap-report.html
