name: OWASP ZAP Security Scan

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Deploy to Hetzner"]
    types:
      - completed

jobs:
  security-scan:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Wait for page to be accessible
      run: |
        echo "Waiting for the application to be accessible..."
        until curl --silent --fail "http://${{secrets.SERVER_IP}}:3000"; do
          echo "Waiting for the server to be ready..."
          sleep 5
        done
        echo "Server is now accessible."

    - name: Install OWASP ZAP
      run: |
        sudo apt update
        sudo apt install -y snapd
        sudo snap install zaproxy --classic

    - name: Run OWASP ZAP Security Scan
      run: |
        zaproxy -cmd -quickurl http://${{ secrets.SERVER_IP }}:3000 -quickout /tmp/zap-report.html

    - name: Upload ZAP Scan Report
      uses: actions/upload-artifact@v4
      with:
        name: zap-scan-report
        path: /tmp/zap-report.html