name: Terraform Hetzner Setup

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        working-directory: terraform
        run: terraform init
        env:
          HCLOUD_TOKEN: ${{ secrets.HETZNER_KEY }}

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -var="hcloud_token=${{ secrets.HETZNER_KEY }}" -var="ssh_public_key=${{ secrets.HETZNER_SSH_PUBLIC }}"
        env:
          HCLOUD_TOKEN: ${{ secrets.HETZNER_KEY }}

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve -var="hcloud_token=${{ secrets.HETZNER_KEY }}" -var="ssh_public_key=${{ secrets.HETZNER_SSH_PUBLIC }}"
        env:
          HCLOUD_TOKEN: ${{ secrets.HETZNER_KEY }}