name: Frontend and Backend Tests

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*' 

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Frontend Dependencies
        working-directory: frontend/blog
        run: npm install

      - name: Run Frontend Tests
        working-directory: frontend/blog
        run: npm test

  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js for Backend
        uses: actions/setup-node@v2
        with:
          node-version: '20' 

      - name: Install Backend Dependencies
        working-directory: backend
        run: npm install

      - name: Start Backend
        working-directory: backend
        run: |
          npm run develop

      - name: Wait for Backend to be Ready
        run: |
          until curl --silent --fail http://localhost:1337; do
            echo "Waiting for backend to be ready..."
            sleep 5
          done

      - name: Run Backend Tests
        working-directory: backend
        run: npm test